FROM mlrlegacydb_mlr_legacy_db

LABEL David Steinich <drsteini@usgs.gov>

############################################
# Setup Liquibase initial run
############################################

COPY ./99_run_liquibase_ci.sh /docker-entrypoint-initdb.d/